# Generated by Django 3.0.1 on 2020-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_firm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='director',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='nip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
