# Generated by Django 3.0.1 on 2020-01-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_auto_20200102_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificate.Firm'),
        ),
    ]
