# Generated by Django 3.0.1 on 2020-01-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_auto_20200102_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
