# Generated by Django 3.0.1 on 2020-01-04 12:55

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0016_certificate_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=certificate.models.upload_location),
        ),
    ]
