# Generated by Django 3.0.1 on 2020-01-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0011_auto_20200102_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='profile',
            new_name='user',
        ),
    ]
